name: 'Action Test'
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - "**.ts"
      - ".github/workflows/action_check.yml"
      - "action.yml"
      - "dist/index.js"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test Action
        uses: ./
        with:
          account: ${{ secrets.TEST_ACCOUNT }}
          project: ${{ secrets.TEST_PROJECT }}

